# Generated by Django 6.0.5 on 2026-05-16 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название зала')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Зал',
                'verbose_name_plural': 'Залы',
                'db_table': 'halls',
            },
        ),
        migrations.CreateModel(
            name='ScreenType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=20, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Тип экрана',
                'verbose_name_plural': 'Типы экранов',
                'db_table': 'screen_types',
            },
        ),
        migrations.CreateModel(
            name='HallScreen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screen_types', to='cinema.hall')),
                ('screen_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.screentype')),
            ],
            options={
                'verbose_name': 'Поддержка экрана залом',
                'verbose_name_plural': 'Поддержка экранов залами',
                'db_table': 'hall_screens',
                'unique_together': {('hall', 'screen_type')},
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveSmallIntegerField(verbose_name='Номер ряда')),
                ('seat_number', models.PositiveSmallIntegerField(verbose_name='Номер места')),
                ('seat_type', models.CharField(choices=[('standard', 'Обычное'), ('vip', 'VIP'), ('sofa', 'Диванчик')], default='standard', max_length=20, verbose_name='Тип места')),
                ('position_x', models.IntegerField(verbose_name='X координата')),
                ('position_y', models.IntegerField(verbose_name='Y координата')),
                ('width', models.IntegerField(default=40, verbose_name='Ширина')),
                ('height', models.IntegerField(default=40, verbose_name='Высота')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='cinema.hall')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
                'db_table': 'seats',
                'ordering': ['hall', 'row_number', 'seat_number'],
                'unique_together': {('hall', 'row_number', 'seat_number')},
            },
        ),
    ]
