# Generated by Django 6.0.5 on 2026-05-16 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Название')),
                ('display_name', models.CharField(max_length=50, verbose_name='Отображаемое имя')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Тип места',
                'verbose_name_plural': 'Типы мест',
                'db_table': 'seat_types',
            },
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinema.seattype', verbose_name='Тип места'),
        ),
    ]
