# Generated by Django 6.0.5 on 2026-05-16 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmScreenFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='film_formats_through', to='movies.film')),
                ('screen_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='film_formats_through', to='cinema.screentype')),
            ],
            options={
                'verbose_name': 'Формат экрана фильма',
                'verbose_name_plural': 'Форматы экранов фильмов',
                'db_table': 'film_screen_formats',
                'unique_together': {('film', 'screen_type')},
            },
        ),
        migrations.AddField(
            model_name='film',
            name='screen_formats',
            field=models.ManyToManyField(related_name='film_formats', through='movies.FilmScreenFormat', to='cinema.screentype'),
        ),
    ]
