# Generated by Django 6.0.5 on 2026-05-16 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_filmscreenformat_film_screen_formats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='trailer',
            new_name='trailer_url',
        ),
        migrations.AddField(
            model_name='film',
            name='trailer_video',
            field=models.FileField(blank=True, null=True, upload_to='film_trailers/', verbose_name='Трейлер (видео)'),
        ),
        migrations.AlterField(
            model_name='film',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='film_posters/', verbose_name='Постер'),
        ),
    ]
