# Generated by Django 6.0.5 on 2026-06-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='send_to_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
