# Generated by Django 6.0.5 on 2026-05-16 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cinema', '0002_seattype_alter_seat_seat_type'),
        ('movies', '0003_rename_trailer_film_trailer_url_film_trailer_video_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_rental_start', models.DateField(verbose_name='Начало проката')),
                ('date_rental_end', models.DateField(verbose_name='Конец проката')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='movies.film')),
            ],
            options={
                'verbose_name': 'Прокат',
                'verbose_name_plural': 'Прокаты',
                'db_table': 'rentals',
                'ordering': ['-date_rental_start'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Время начала')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='cinema.hall')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='showtimes.rental')),
                ('screen_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.screentype')),
            ],
            options={
                'verbose_name': 'Сеанс',
                'verbose_name_plural': 'Сеансы',
                'db_table': 'sessions',
                'ordering': ['start_time'],
                'unique_together': {('hall', 'start_time')},
            },
        ),
    ]
