# Generated by Django 6.0.5 on 2026-05-16 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Телефон')),
                ('password', models.CharField(max_length=255, verbose_name='Пароль (hash)')),
                ('receive_newsletter', models.BooleanField(default=False, verbose_name='Получать рассылку')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('patronimic', models.CharField(blank=True, max_length=50, verbose_name='Отчество')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('last_password_change', models.DateTimeField(auto_now_add=True)),
                ('reset_code', models.CharField(blank=True, max_length=6, null=True, verbose_name='Код сброса')),
                ('reset_code_created_at', models.DateTimeField(blank=True, null=True, verbose_name='Время создания кода')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'db_table': 'customers',
                'ordering': ['-created_at'],
            },
        ),
    ]
